### PR TITLE
Fixed response types for Cart and CartItem

### LINKED ISSUE #342: product_id property is missing from TS CartItem type
It seems the `product_id` property is present on the `OrderItem` type but not on the `CartItem` type.

But `CartItem`s returned from a `Cart.Items()` call do have the `product_id` property.

### PR DESCRIPTION
**Pull request by dusanradovanovic**
## Type

* ### Fix
## Description

This PR is fixing type definitions for Cart and CartItem types. Tests were also updated to check for TypeScript properties for these types. Closes #342 .

### CODE REVIEW

File: src/types/cart.d.ts [hunk 1]
```diff
@@ -59,45 +60,84 @@ export interface Cart extends Identifiable, CartBase {
 }
 
 export interface CartItemBase {
-  tax: {}[];
-  quantity: number;
+}
```
Comment (shaunmaharaj) [inline src/types/cart.d.ts:63]: What’s the purpose of the empty interface? CartItem the the only interface extending this - can we remove it?

**Comment by shaunmaharaj** [comment]
Thank you for the quick turnaround on this one Dusan! Wonderful work here!

File: src/types/cart.d.ts (hunk 1 above)
Comment (dusanradovanovic) [reply src/types/cart.d.ts:63]: `...Base` interfaces are there for extending. Customers can add flow defined props there and they will bubble up and show in `CartItem` as well. I didn't want to merge them into one for consistency since other types have non-empty Base interfaces.
